source "https://rubygems.org"
gem "rack", ">= 1.6.11" # added due to GitHub alert
gem "rack-protection", ">= 1.5.5" # added due to GitHub alert
gem "sinatra", "~>1.4.7"
gem "sinatra-contrib"
gem "erubis"
ruby "2.6.0"
gem "rack-test" # added for testing
gem "minitest" # added for testing
gem "redcarpet" # for Markdown rendering
gem "bcrypt" # for pswd encryption
