# Gemfile is unused; using versions of Gems installed by other projs ?

source "https://rubygems.org"
gem "rack", ">= 1.6.12" # added due to GitHub alert

gem "sinatra", ">= 2.2.0" # updated due to GitHub alert
gem "sinatra-contrib"
gem "erubis"
