source "https://rubygems.org"
# gem "rack", ">= 1.6.12" # updated due to GitHub alert
gem "rack", "~> 2.1.4" # updated due to GitHub alert
gem "rack-protection", ">= 1.5.5" # added due to GitHub alert

# gem "sinatra", "~>1.4.7"
gem "sinatra", "~> 2.0.0"
gem "sinatra-contrib"
gem "erubis"
