source "https://rubygems.org"

# gem "rack", ">= 1.6.12" # added due to GitHub alert
gem "rack", "~> 2.1.4" # updated due to GitHub alert
gem "rack-protection", ">= 1.5.5" # added due to GitHub alert

# gem "sinatra", "~>1.4.7"
gem "sinatra", "~> 2.0.0" # updated for compatibility w/ "rack"
gem "sinatra-contrib"
gem "erubis"

ruby "2.6.0"
group :production do
  # gem "puma", ">= 4.3.5" # updated due to GitHub alert
  gem "puma", ">= 4.3.8" # updated due to GitHub alert
end
